import { Anchor, ChevronRight, Compass, Hammer, PackagePlus, Sailboat, ShieldCheck, Users, Wheat } from 'lucide-react';
import { expeditionChapters, type ExpeditionChapter, type ExpeditionId, type ExpeditionSupplies } from '../data/expeditions';

export type ExpeditionPhase = 'planning' | 'ready' | 'voyage' | 'arrived';
interface ExpeditionHUDProps { selectedId: ExpeditionId; supplies: ExpeditionSupplies; phase: ExpeditionPhase; progress: number; spokenCharacters: number; onSelect: (id: ExpeditionId) => void; onSupply: (resource: keyof ExpeditionSupplies) => void; onLaunch: () => void; onReturn: () => void; }
const percent = (value: number) => `${Math.round(value)}%`;
const requirementMet = (value: number, requirement: number) => value >= requirement;

function ResourceRow({ icon, label, resource, value, requirement, disabled, onSupply }: { icon: React.ReactNode; label: string; resource: keyof ExpeditionSupplies; value: number; requirement: number; disabled: boolean; onSupply: (resource: keyof ExpeditionSupplies) => void; }) {
  const met = requirementMet(value, requirement);
  return <div className={`resource-row ${met ? 'resource-row--ready' : ''}`}><span className="resource-row__icon">{icon}</span><div className="resource-row__main"><div><strong>{label}</strong><span>{value} / {requirement}</span></div><span className="resource-meter"><i style={{ width: percent(Math.min(100, value)) }} /></span></div><button type="button" onClick={() => onSupply(resource)} disabled={disabled || value >= 100} aria-label={`Пополнить: ${label}`}><PackagePlus size={15} /></button></div>;
}
function ChapterButton({ chapter, active, onSelect }: { chapter: ExpeditionChapter; active: boolean; onSelect: () => void }) {
  return <button type="button" className={`chapter-card ${active ? 'chapter-card--active' : ''}`} onClick={onSelect}><span className="chapter-card__index">{chapter.durationLabel}</span><span className="chapter-card__copy"><strong>{chapter.title}</strong><small>{chapter.subtitle}</small></span><ChevronRight size={16} /></button>;
}
export function ExpeditionHUD({ selectedId, supplies, phase, progress, spokenCharacters, onSelect, onSupply, onLaunch, onReturn }: ExpeditionHUDProps) {
  const chapter = expeditionChapters.find((item) => item.id === selectedId) ?? expeditionChapters[0];
  const requirementsMet = Object.entries(chapter.requirements).every(([key, value]) => supplies[key as keyof ExpeditionSupplies] >= value);
  const dialogueMet = spokenCharacters >= 2;
  const ready = requirementsMet && dialogueMet;
  if (phase === 'voyage' || phase === 'arrived') return <aside className="voyage-hud glass-panel" aria-label="Состояние экспедиции"><div className="voyage-hud__heading"><span className="voyage-hud__icon"><Sailboat size={20} /></span><div><span className="eyebrow">Экспедиция</span><strong>{chapter.title}</strong><small>{chapter.subtitle}</small></div></div><div className="voyage-hud__progress"><div><span>{phase === 'arrived' ? 'Маршрут завершён' : 'Путь экспедиции'}</span><strong>{Math.round(progress * 100)}%</strong></div><span><i style={{ width: percent(progress * 100) }} /></span></div><p>{phase === 'arrived' ? chapter.historicalFrame : chapter.objective}</p>{phase === 'arrived' && <button type="button" className="primary-action" onClick={onReturn}>Вернуться в поселение</button>}</aside>;
  return <aside className="expedition-hud glass-panel" aria-label="Подготовка экспедиции"><div className="expedition-hud__topline"><div><span className="eyebrow">Совет экспедиции</span><h2>Подготовить путь</h2></div><span className={`readiness-seal ${ready ? 'readiness-seal--ready' : ''}`}>{ready ? <ShieldCheck size={17} /> : <Anchor size={17} />}{ready ? 'готово' : 'подготовка'}</span></div><div className="chapter-list">{expeditionChapters.map((item) => <ChapterButton key={item.id} chapter={item} active={item.id === selectedId} onSelect={() => onSelect(item.id)} />)}</div><section className="chapter-brief"><div className="chapter-brief__metrics"><span><Compass size={14} /> {chapter.departureYear}–{chapter.arrivalYear}</span><span><Users size={14} /> {chapter.crew} человек</span><span><Anchor size={14} /> риск: {chapter.risk}</span></div><h3>{chapter.objective}</h3><p>{chapter.historicalFrame}</p></section><div className="resource-stack"><ResourceRow icon={<Wheat size={16} />} label="Провизия" resource="provisions" value={supplies.provisions} requirement={chapter.requirements.provisions} disabled={phase !== 'planning'} onSupply={onSupply} /><ResourceRow icon={<Hammer size={16} />} label="Древесина" resource="timber" value={supplies.timber} requirement={chapter.requirements.timber} disabled={phase !== 'planning'} onSupply={onSupply} /><ResourceRow icon={<Sailboat size={16} />} label="Парусина" resource="sailcloth" value={supplies.sailcloth} requirement={chapter.requirements.sailcloth} disabled={phase !== 'planning'} onSupply={onSupply} /></div><div className="readiness-checks"><span className={dialogueMet ? 'is-complete' : ''}><i />Поговорить минимум с двумя членами команды ({spokenCharacters}/2)</span><span className={requirementsMet ? 'is-complete' : ''}><i />Собрать минимальный запас для выбранной главы</span></div><button type="button" className="primary-action expedition-launch" onClick={onLaunch} disabled={!ready}><Sailboat size={18} /><span><strong>Начать экспедицию</strong><small>{ready ? 'Корабль выйдет из фьорда' : 'Завершите подготовку'}</small></span></button></aside>;
}
