import { Line } from '@react-three/drei';
import { useFrame } from '@react-three/fiber';
import { useMemo, useRef } from 'react';
import * as THREE from 'three';
import { makeGroundCurve } from '../lib/flatMap';
import type { VikingRoute, VikingStop } from '../types';
import { LongshipModel } from './LongshipModel';
interface GroundRouteProps { route: VikingRoute; timelineYear: number; emphasized: boolean; shipsEnabled: boolean; shipSpeed: number; compact: boolean; journeyRouteId?: string | null; journeyProgress?: number; }
function Longship({curve,progress,speed,color,compact}:{curve:THREE.CatmullRomCurve3;progress:number;speed:number;color:string;compact:boolean}){const groupRef=useRef<THREE.Group>(null);const sailRef=useRef<THREE.Mesh>(null);const current=useRef(progress);useFrame(({clock},rawDelta)=>{const group=groupRef.current;if(!group)return;const delta=Math.min(rawDelta,1/30);current.current=THREE.MathUtils.damp(current.current,progress,5.6*speed,delta);const t=THREE.MathUtils.clamp(current.current,.015,.985);const point=curve.getPointAt(t);const tangent=curve.getTangentAt(t).normalize();group.position.lerp(point,1-Math.exp(-delta*10));group.rotation.y=THREE.MathUtils.damp(group.rotation.y,Math.atan2(tangent.x,tangent.z),8,delta);group.position.y=point.y+Math.sin(clock.elapsedTime*1.75)*.014;group.rotation.z=Math.sin(clock.elapsedTime*1.18)*.022;if(sailRef.current)sailRef.current.rotation.y=Math.sin(clock.elapsedTime*.72)*.025});return <group ref={groupRef} scale={compact ? .52 : .66}><LongshipModel compact={compact} accent={color} sailRef={sailRef}/></group>}
const segmentProgress=(start:VikingStop,end:VikingStop,year:number)=>THREE.MathUtils.clamp((year-start.year)/Math.max(1,end.year-start.year),0,1);
export function GroundRoute({route,timelineYear,emphasized,shipsEnabled,shipSpeed,compact,journeyRouteId=null,journeyProgress=0}:GroundRouteProps){const segments=useMemo(()=>route.stops.slice(1).map((end,index)=>{const start=route.stops[index];return{start,end,curve:makeGroundCurve(start,end,index+route.startYear)}}),[route]);let latest=-1;segments.forEach(({start},index)=>{if(timelineYear>=start.year)latest=index});const activeJourney=journeyRouteId===route.id;const normalized=THREE.MathUtils.clamp(journeyProgress,0,.999999);const journeySegment=activeJourney?Math.min(segments.length-1,Math.floor(normalized*segments.length)):-1;const local=activeJourney?normalized*segments.length-journeySegment:0;return <group>{segments.map(({start,end,curve},index)=>{const chronology=segmentProgress(start,end,timelineYear);const progress=activeJourney?(index<journeySegment?1:index===journeySegment?Math.max(.02,local):0):chronology;if(progress<=0)return null;const full=curve.getPoints(compact?42:92);const points=full.slice(0,Math.max(2,Math.ceil(progress*(full.length-1))+1));return <group key={`${start.id}-${end.id}`}>{!compact&&emphasized&&<Line points={points} color={route.accent} lineWidth={5} transparent opacity={.1} depthWrite={false}/>}<Line points={points} color={route.color} lineWidth={emphasized?(compact?1.8:2.7):1} transparent opacity={emphasized?.92:.16} depthWrite={false}/>{shipsEnabled&&emphasized&&((activeJourney&&index===journeySegment)||(!activeJourney&&index===latest&&chronology>.04))&&<Longship curve={curve} progress={activeJourney?local:Math.max(.04,chronology*.92)} speed={shipSpeed} color={route.accent} compact={compact}/>}</group>})}</group>}
