import { useFrame } from '@react-three/fiber';
import { useEffect, useMemo, useRef } from 'react';
import * as THREE from 'three';
import { createLandMask, createLandMaskTexture, createTerrainGeometry, MAP_DEPTH, MAP_WIDTH } from '../lib/flatMap';
import type { RenderQuality } from '../types';
interface MapSurfaceProps { quality: Exclude<RenderQuality,'auto'>; }
function WaterPlane({compact,maskTexture}:{compact:boolean;maskTexture:THREE.Texture}){const materialRef=useRef<THREE.ShaderMaterial>(null);const uniforms=useMemo(()=>({uTime:{value:0},uLandMask:{value:maskTexture},uCompact:{value:compact?1:0},uDeep:{value:new THREE.Color('#06191f')},uShallow:{value:new THREE.Color('#13505a')},uSky:{value:new THREE.Color('#7ca3a8')}}),[compact,maskTexture]);useFrame(({clock})=>{if(materialRef.current)materialRef.current.uniforms.uTime.value=clock.elapsedTime});return <mesh rotation={[-Math.PI/2,0,0]} position={[0,.018,0]} receiveShadow><planeGeometry args={[MAP_WIDTH+1.8,MAP_DEPTH+1.8,compact?32:160,compact?18:84]}/><shaderMaterial ref={materialRef} uniforms={uniforms} transparent depthWrite={false} side={THREE.DoubleSide} vertexShader={`uniform float uTime;uniform float uCompact;varying vec2 vUv;varying vec3 vWorld;varying float vWave;void main(){vUv=uv;vec3 p=position;float waveA=sin((p.x*1.5+p.y*.72)+uTime*.72)*.018;float waveB=cos((p.y*2.15-p.x*.34)-uTime*.48)*.012;float waveC=sin((p.x+p.y)*3.9+uTime*.31)*.005;float wave=(waveA+waveB+waveC)*mix(1.,.22,uCompact);p.z+=wave;vec4 world=modelMatrix*vec4(p,1.);vWorld=world.xyz;vWave=wave;gl_Position=projectionMatrix*viewMatrix*world;}`} fragmentShader={`uniform float uTime;uniform sampler2D uLandMask;uniform vec3 uDeep;uniform vec3 uShallow;uniform vec3 uSky;varying vec2 vUv;varying vec3 vWorld;varying float vWave;float waveLine(vec2 p,float scale,float speed){return sin((p.x+p.y*.42)*scale+uTime*speed)*.5+.5;}void main(){vec2 mapUv=vec2((vWorld.x/${MAP_WIDTH.toFixed(1)})+.5,.5-(vWorld.z/${MAP_DEPTH.toFixed(1)}));float land=texture2D(uLandMask,clamp(mapUv,0.,1.)).r;float coast=smoothstep(.08,.42,land)-smoothstep(.42,.78,land);float depthMix=smoothstep(0.,.65,land);vec3 viewDirection=normalize(cameraPosition-vWorld);float fresnel=pow(1.-max(dot(viewDirection,vec3(0.,1.,0.)),0.),2.2);float caustic=waveLine(vWorld.xz,4.5,.7)*waveLine(vWorld.zx,6.7,-.42);vec3 color=mix(uDeep,uShallow,depthMix*.72+caustic*.08+vWave*2.2);color=mix(color,uSky,fresnel*.34);color+=coast*(.22+caustic*.16)*vec3(.76,.84,.78);float alpha=mix(.92,.62,depthMix*.55);gl_FragColor=vec4(color,alpha);}`}/></mesh>}
const TerrainSkirt=()=> <mesh position={[0,-.31,0]} receiveShadow><boxGeometry args={[MAP_WIDTH+.28,.58,MAP_DEPTH+.28]}/><meshStandardMaterial color="#0b1211" roughness={.98} metalness={.02}/></mesh>;
export function MapSurface({quality}:MapSurfaceProps){const compact=quality==='battery';const mask=useMemo(()=>createLandMask(quality==='high'?1024:compact?448:720),[compact,quality]);const geometry=useMemo(()=>createTerrainGeometry(quality==='high'?240:compact?92:168,quality==='high'?128:compact?50:88,mask),[compact,mask,quality]);const maskTexture=useMemo(()=>createLandMaskTexture(mask),[mask]);useEffect(()=>()=>{geometry.dispose();maskTexture.dispose()},[geometry,maskTexture]);return <group><TerrainSkirt/><mesh geometry={geometry} receiveShadow castShadow={!compact}><meshStandardMaterial vertexColors roughness={.92} metalness={.02} envMapIntensity={.36} flatShading={compact}/></mesh><WaterPlane compact={compact} maskTexture={maskTexture}/><mesh rotation={[-Math.PI/2,0,0]} position={[0,.027,0]}><ringGeometry args={[4.95,5.02,128]}/><meshBasicMaterial color="#d0b578" transparent opacity={.08} depthWrite={false}/></mesh></group>}
