import { Html } from '@react-three/drei';
import { useFrame } from '@react-three/fiber';
import { useMemo, useRef } from 'react';
import * as THREE from 'three';
import { vikingCharacters, type VikingCharacter } from '../data/dialogues';
import { latLonToMap } from '../lib/flatMap';
import { LongshipModel } from './LongshipModel';
import { VikingActor } from './VikingActor';
interface VikingCampProps { compact:boolean; onSpeak:(character:VikingCharacter)=>void; }
function Campfire({compact}:{compact:boolean}){const ref=useRef<THREE.Mesh>(null);useFrame(({clock})=>{if(ref.current){ref.current.scale.y=.88+Math.sin(clock.elapsedTime*8.2)*.12;ref.current.rotation.y=clock.elapsedTime*.9}});return <group position={[.28,.04,.18]}><mesh><torusGeometry args={[.1,.024,8,20]}/><meshStandardMaterial color="#2b2722"/></mesh><mesh ref={ref} position={[0,.15,0]}><coneGeometry args={[.07,.3,9]}/><meshStandardMaterial color="#ff8a32" emissive="#ff5b1f" emissiveIntensity={2.2}/></mesh>{!compact&&<pointLight position={[0,.34,0]} color="#ff9b47" intensity={3.4} distance={1.7}/>}</group>}
export function VikingCamp({compact,onSpeak}:VikingCampProps){const origin=latLonToMap(59.1,10.1,.16);const pines=useMemo(()=>[[-1.32,-.74,1.25],[-1.05,-.96,.92],[-.7,-1.05,.8],[1.25,-.74,1.12]],[]);return <group position={origin} scale={compact ? .72 : .88}><mesh receiveShadow position={[0,-.02,0]}><cylinderGeometry args={[1.65,1.82,.1,48]}/><meshStandardMaterial color="#344936" roughness={1}/></mesh><mesh position={[-.18,.22,-.3]} castShadow={!compact}><boxGeometry args={[1.12,.42,.52]}/><meshStandardMaterial color="#65432d"/></mesh><mesh position={[-.18,.53,-.3]} rotation={[0,Math.PI/4,0]} scale={[1.55,.62,.92]}><coneGeometry args={[.52,.62,4]}/><meshStandardMaterial color="#493326"/></mesh><mesh position={[.92,.15,.08]}><boxGeometry args={[.56,.28,.38]}/><meshStandardMaterial color="#70492f"/></mesh><mesh position={[-.65,.05,.83]}><boxGeometry args={[1.7,.08,.34]}/><meshStandardMaterial color="#6b4b31"/></mesh><Campfire compact={compact}/><group position={[-.58,.13,1.08]} scale={.52}><LongshipModel compact={compact} accent="#a94b35"/></group>{pines.map(([x,z,s])=><group key={`${x}-${z}`} position={[x,0,z]} scale={s}><mesh position={[0,.13,0]}><cylinderGeometry args={[.028,.042,.28,7]}/><meshStandardMaterial color="#4a2e20"/></mesh><mesh position={[0,.45,0]}><coneGeometry args={[.18,.6,compact?7:12]}/><meshStandardMaterial color="#1d4036"/></mesh></group>)}{vikingCharacters.map(character=><VikingActor key={character.id} character={character} compact={compact} onSpeak={onSpeak}/>)}<Html center position={[-.18,1.2,-.32]} distanceFactor={10}><div className="camp-label"><strong>Хавнфьорд</strong><span>поселение · начало хроники</span></div></Html></group>}
